### ISSUE TITLE
Malware in your repo

### ISSUE THREAD

**Issue by orlikoski** [andrevenancio/tease#1]
Are you aware that https://github.com/andrevenancio/tease/blob/master/test.js is malicious and associated with the ESLint NPM malware incident?  This malware caused NPM to revoke all tokens since it steals NPM tokens. 

https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes
https://github.com/eslint/eslint-scope/issues/39
https://status.npmjs.org/incidents/dn7c1fgrr7ng

**Comment by andrevenancio** [comment]
Hey @orlikoski good shout. I was reading all about it yesterday and since the pastebin got deleted I wanted to check what the malicious code was doing. unfortunatelly created the file on my already open terminal window and that got pushed with code today! How did you find this btw? Thanks for the shout! removed

**Comment by orlikoski** [comment]
It was found by a college of mine who was searching Github for other signs of the malicious code
